###
GET http://localhost:5000

### Register a user 
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"moon2",
    "password":"123"
}
### Login a user at /auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"moon2",
    "password":"123"
}

###check for todos route
GET http://localhost:5000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MzAzMDM0LCJleHAiOjE3MzczODk0MzR9.5HsoDES2ZDHadILw8bV07uY9Jo72-HnO5Gs2InfAcXU


###create a new todo
POST http://localhost:5000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3MzAzMDM0LCJleHAiOjE3MzczODk0MzR9.5HsoDES2ZDHadILw8bV07uY9Jo72-HnO5Gs2InfAcXU
Content-Type: application/json

{
    "todoData": "Coding"
}

